# Generated by Django 5.0 on 2024-01-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0006_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
