# Generated by Django 5.0 on 2024-01-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0007_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_duration', models.CharField(max_length=255)),
                ('course_file', models.FileField(upload_to='course')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.tutor')),
                ('technology', models.ManyToManyField(to='Tutor.technology')),
            ],
        ),
    ]
